---
include:
  - project: confirm/infrastructure/ci
    file: python-package/.gitlab-ci.yml
  - project: confirm/infrastructure/ci
    file: docs/.gitlab-ci.yml
  - project: confirm/infrastructure/ci
    file: deploy/.gitlab-ci.yml

variables:
  MCI_DOCKER_DEPLOY_SERVICES: docs

Build docs:
  stage: build
  variables:
    DATA_DIR: /data

Build vendor JS:
  stage: build
  image: ${MCI_DOCKER_REGISTRY}/base/node-dev:latest
  script:
    - make develop-node
    - make vendor-js
  artifacts:
    name: vendor
    paths:
      - confirm/typr/static/js/vendor

Build package:
  needs:
    - job: Build vendor JS
