---
services:


  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  #
  # 🌍 Docs.
  #
  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  docs:

    #
    # 🔨 Build
    #

    build:
      context: .
      dockerfile: Dockerfiles/docs
      args:
        - MCI_DOCKER_REGISTRY

    image: ${MCI_DOCKER_REGISTRY}/typarr/docs:${MCI_DOCKER_TAG}

    #
    # ⚡ Resources
    #

    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '64M'

    #
    # 🔒 Security
    #

    security_opt:
      - no-new-privileges:true

    read_only: true

    tmpfs:
      - /tmp

    #
    # 🔄 Restart policy
    #

    restart: unless-stopped

  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  #
  # 📝 Typarr.
  #
  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  typarr:

    build:
      context: .
      dockerfile: Dockerfiles/typarr
      args:
        - MCI_DOCKER_REGISTRY

    image: ${MCI_DOCKER_REGISTRY}/typarr/typarr:${MCI_DOCKER_TAG}

