---
services:

  typarr:

    image: ghcr.io/confirm/typarr

    environment:
      TYPARR_OIDC_DISCOVERY_URL: https://sso.example.com/.well-known/openid-configuration
      TYPARR_OIDC_CLIENT_SECRET: change-me
      TYPARR_TRUSTED_PROXIES: '*'

    ports:
      - '5000:5000'

    read_only: true

    tmpfs:
      - /tmp

    volumes:
      - data:/data

    restart: unless-stopped

volumes:
  data:
