---
services:

  typr:

    image: harbor.confirm.ch/typr/typr

    environment:
      OIDC_DISCOVERY_URL: https://sso.example.com/.well-known/openid-configuration
      OIDC_CLIENT_SECRET: change-me

    ports:
      - '5000:5000'

    read_only: true

    tmpfs:
      - /tmp

    volumes:
      - data:/data

    restart: unless-stopped

volumes:
  data:
